### PR TITLE
Make dynamic blocks after mod init instead of via registry listener

### PR DESCRIPTION
**Pull request by exaskye**
I encountered a registry desync between client/server in a modpack I help maintain for Quilt 1.18.2, caused by DimDoors' dynamic registry. This has likely never been seen on Fabric as Fabric's registry sync is much more robust than Quilt's, at least on 1.18.

Registering things in a registry callback is kind of dangerous, as it has unpredictable effects on registry order. In our case, on the client dimdoors was coming first, while on the server dimdoors was coming after the source mods' blocks. This caused all normal doors to be dimensional, and all dimensional doors to be normal.

This PR defers dynamic generation until after mod initialization, using a trick where the server/client initializers run after the common initializer — this provides a way to perform a "postinit" on Fabric/Quilt. This should, in general, be a much safer way to do this, and also not prone to infinite loops from other dynamic registration.

We've tested this on our server that was affected by the bug, and the change is logically sound.

### CODE REVIEW

**Comment by Waterpicker** [comment]
Would this also be useful for the future port back to forge via mulit platform?

**Comment by exaskye** [comment]
Forge does not allow dynamic registration. Even something as simple as not registering things that are disabled via config is not allowed.

**Comment by GiantLuigi4** [comment]
> Forge does not allow dynamic registration. Even something as simple as not registering things that are disabled via config is not allowed.

That ain’t quite true
It’s possible, and very easy, but discouraged, because idk why

**Comment by exaskye** [comment]
I don't know, or really care. It's just another entry on my very long list of reasons I don't use or dev for Forge.

**Comment by Waterpicker** [comment]
Lets not turned dimdoor's repo become a battlefield. Plenty of other places for that.

**Comment by asiekierka** [comment]
Fabric's registry system was explicitly designed to allow both order desynchronization (as it can happen during some types of mod configuration/assortment differences between server and client too) and registering things in a register callback (to allow other mods to respond to new blocks being added dynamically; for example, Unlimited Chisel Works would have benefited a lot from it, and that mod was the inspiration for this feature when I proposed it. Infinite loops were a concern, but - as with Fabric's general design principle - it was hoped that modders avoid bringing scenarios where an actual infinite loop would occur.).

If Quilt doesn't support these, then that sounds to me like a compatibility issue; I see no problem with patching it mod-side in a legacy version, but I think the issue, at least as presented, should be raised with Quilt.

**Comment by exaskye** [comment]
If you end up wanting this, feel free to merge it manually, but I'm not interested in where the PR discussion has gone. I had a need and made a patch, and offered it as a PR as a courtesy. I don't care whose fault it is or how it works under Forge.

**Pull request closed without merging**
