### PR TITLE
Optimize assets

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression made with the Leanify tool. Also, update the Gradle version to the newest release.

### CODE REVIEW

**Comment by Waterpicker** [comment]
I'm gonna hazard a guess that you pushed the textures through a program that forces them to be indexed?

**Comment by K0-RR** [comment]
I'm not sure what this tool does, all I know is that it compressed the assets lossless. I tried to read about indexing a PNG but I had trouble understanding some technical details. In the past I used Oxipng for work like this one and its output was mentioning something about changing how are colors registered (?)

**Comment by Waterpicker** [comment]
Sorry its been years since I poked this. If I recall, its called color indexing.

**Comment by Waterpicker** [comment]
Closing this as I'm gonna an updated version manually on my end.

**Pull request closed without merging**
