### PR TITLE
1.12 cubic chunks

### PR DESCRIPTION
**Pull request by Mysticpasta1**

### CODE REVIEW

**Comment by TheComputerizer** [comment]
Not sure how much of the newer stuff this will overwrite so I will probably have to go over it manually

**Comment by Mysticpasta1** [comment]
sounds good to me

**Comment by Waterpicker** [comment]
Has this been resolved now?

**Comment by Mysticpasta1** [comment]
no, someone needs to fix the conflicting files

**Comment by Yobrocharlie** [comment]
Wait what exactly will cubic chunks do?

**Comment by Mysticpasta1** [comment]
> Wait what exactly will cubic chunks do?

Infinite Height mod for 1.12.2

**Comment by Yobrocharlie** [comment]
How nice, I could do a few things with that

**Comment by Waterpicker** [comment]
Closing for now.

**Pull request closed without merging**
